DROP USER Week2CDB CASCADE;
/*******************************************************************************
   Create database
********************************************************************************/
CREATE USER Week2CDB
IDENTIFIED BY mypassword
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to Week2CDB;
GRANT resource to Week2CDB;
GRANT create session TO Week2CDB;
GRANT create table TO Week2CDB;
GRANT create view TO Week2CDB;

conn Week2CDB/mypassword

/
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;


    CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMP_FIRSTNAME VARCHAR2(30) , 
    EMP_LASTNAME VARCHAR2(30) , 
    DEPARTMENT_ID INTEGER,
    SALARY NUMBER(10, 0),
    EMP_EMAIL VARCHAR2(50) 
    );
    /
    CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID INTEGER PRIMARY KEY,
     DEPARTMENT_NAME VARCHAR2(30) 
     );
     /

    ALTER TABLE EMPLOYEE
    ADD  CONSTRAINT FK_EMP_DEP FOREIGN KEY  (DEPARTMENT_ID)  REFERENCES DEPARTMENT (DEPARTMENT_ID);
    /
    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

--CAR ID TRIGGER GENERATOR
 CREATE SEQUENCE EMPIDSEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 100;

CREATE OR REPLACE TRIGGER  emp_trigga
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
SELECT EMPIDSEQ.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/
    
    
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL, DEPARTMENT_ID)
    VALUES (EMPIDSEQ.NEXTVAL,'Larry','Monsen', 25000, 'larry@gmail.com', 1);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL, DEPARTMENT_ID)
    VALUES (EMPIDSEQ.NEXTVAL,'Emily','Smith', 78000, 'emily@gmail.com', 1);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL, DEPARTMENT_ID)
    VALUES (EMPIDSEQ.NEXTVAL,'Adams','Sarr', 58000, 'adams@gmail.com', 3);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL, DEPARTMENT_ID)
    VALUES (EMPIDSEQ.NEXTVAL,'Abdoul','Tylor', 45000, 'abdoul@aol.com', 2);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL, DEPARTMENT_ID)
    VALUES (EMPIDSEQ.NEXTVAL,'Moussa','Alstrom', 45000, 'moussa@yahoo.com', 2);
    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL, DEPARTMENT_ID)
    VALUES (EMPIDSEQ.NEXTVAL,'Sophy','Kareme', 55000, 'sphie@aol.com', 2);


--------------------------------------------------------------------------------------------------------------------------------------------------------------

--CAR ID TRIGGER GENERATOR
 CREATE SEQUENCE DEPIDSEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 5;

CREATE OR REPLACE TRIGGER  dep_trigga
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
SELECT DEPIDSEQ.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;

    
    
    INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (DEPIDSEQ.NEXTVAL,'ACCOUNTING');
       INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (DEPIDSEQ.NEXTVAL,'HUMAN RESOURCE');
       INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (DEPIDSEQ.NEXTVAL,'INFO- TECH');
       INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (DEPIDSEQ.NEXTVAL,'AMINISTRATION');








